apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
    shortNames:
      - app
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              properties:
                source:
                  type: object
                  properties:
                    repoURL:
                      type: string
                    path:
                      type: string
                    targetRevision:
                      type: string
                    helm:
                      type: object
                      properties:
                        parameters:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                destination:
                  type: object
                  properties:
                    server:
                      type: string
                    namespace:
                      type: string
                project:
                  type: string
                syncPolicy:
                  type: object
                  properties:
                    automated:
                      type: object
                      properties:
                        prune:
                          type: boolean
                        selfHeal:
                          type: boolean
                    syncOptions:
                      type: array
                      items:
                        type: string
            status:
              type: object
              properties:
                operationState:
                  type: object
                  properties:
                    phase:
                      type: string
                    message:
                      type: string
                health:
                  type: object
                  properties:
                    status:
                      type: string
                sync:
                  type: object
                  properties:
                    status:
                      type: string
                    comparedTo:
                      type: object
                      properties:
                        source:
                          type: object
                          properties:
                            repoURL:
                              type: string
                            path:
                              type: string
                        destination:
                          type: object
                          properties:
                            server:
                              type: string
                            namespace:
                              type: string
